server:
  port: 8099
spring:
  application:
    name:agendaService
main:
  allow-bean-definition-overriding: true
data:
  data:
    mongodb:
      database: agendasservice_db
      host: mongo  # Cambia esto a 'mongo'
      port: 27017  # Cambia el puerto a 27017
