server:
  port: 8099

spring:
  application:
    name: agendaService
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: agendasservice_db
      host: mongo_DB
      port: 27017

